version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Running migrations...
      - npm run prisma:deploy
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'